NUMPY

In [4]:
import numpy as np

In [5]:
#generar un ARRAY a partir de listas

a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [6]:
#array bidimensional
a2 = np.array([(1, 2, 3), (4, 5, 6)])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#array tridimensional FOTO
a3 = np.array([[[1, 2, 3]]], [3, 4, 5]],[[1, 2, 3],[3, 4, 5]],
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#podemos generar arrays de otras maneras. A partir de datos que ya existen. Podremos hacerlo con funciones. av es vacio. 
av = np.empty([4, 3])
av

array([[2.38638529e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.70315438e-066],
       [8.78191400e-071, 1.72398376e-047, 3.46799077e+179],
       [7.40906717e-038, 2.14587205e+184, 1.76002574e-076]])

In [9]:
#podemos generar arrays llenos de valores
az = np.zeros([3, 5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
ao = np.ones([3, 5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
af = np.full([3, 5], 9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [12]:
#generación de arrays de identidad. En su trasversal tienen 1 y 0
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#pedir información
np.info(np.arrange)

In [14]:
np.info(np.linspace)
a1 = np.linspace(1, 100, 20)
a1

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [15]:
#genera numeros aleatorios. También nos completaría los datos que nos faltan*
aran = np.random.random([2, 3])
aran

array([[0.80820024, 0.96453946, 0.09202559],
       [0.81634625, 0.08880042, 0.16757525]])

In [16]:
#para saber la dimensión del array
aran.ndim

2

In [23]:
#para saber el tamaño del array
aran.shape


(2, 3)

In [22]:
aran.size

6

In [21]:
#saber el tipo de datos
aran.dtype


dtype('float64')

In [24]:
at = np.array(['hola, mundo'])
at.dtype

dtype('<U11')

In [ ]:
#los tipos de datos en los array tienen que ser los mismos.

In [26]:
a1

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [27]:
#trasnformar los datos en enteros
np.info(a1.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [28]:
a1.astype('i')

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [30]:
#ordenar un array. Permite pasar un array e indicar los ejes por lo que puedo ordenarlo. 
np.sort(a1)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [31]:
aran

array([[0.80820024, 0.96453946, 0.09202559],
       [0.81634625, 0.08880042, 0.16757525]])

In [33]:
np.info(np.sort)

 sort(a, axis=-1, kind=None, order=None)

Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still b

In [35]:
np.sort(aran, axis=0)


array([[0.80820024, 0.08880042, 0.09202559],
       [0.81634625, 0.96453946, 0.16757525]])

In [38]:
#conjuntos de funciones estadísticas sencillas. MIN, MAX, MED, DESV, VALOR ABS, VAL UNICOS...

arr = np.array([2, 4, 5, 0, 6, 1, 5, 4, 1, -3])


In [39]:
np.absolute(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [40]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 5, 4, 1, 3])

In [41]:
np.cumsum(arr)

array([ 2,  6, 11, 11, 17, 18, 23, 27, 28, 25])

In [42]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [43]:
np.exp(arr)

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 1.00000000e+00,
       4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01,
       2.71828183e+00, 4.97870684e-02])

In [46]:
np.prod(arr)

0

In [50]:
np.NaN

nan

In [52]:
for x in aran:
    print(x)

[0.80820024 0.96453946 0.09202559]
[0.81634625 0.08880042 0.16757525]


In [53]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [54]:
#imprimir un rango
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 4
2 5
3 0
4 6
5 1
6 5
7 4
8 1
9 -3


In [55]:
#iterar sobre un elemento de dos dimensiones. Anidaremos una iteración sobre otra aunque no sea muy optimo pero es posible
for x in aran:
    for y in x:
        print(y)

0.8082002443335065
0.9645394619192165
0.09202558650887316
0.8163462468809399
0.08880042122316989
0.1675752485604155


In [56]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

TypeError: 'numpy.int64' object is not iterable

In [60]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [61]:
for x in np.nditer(a3):
    print(x)

1
2
3
4
5
6
7
8
9


In [62]:
#otra opción
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [63]:
for pos, x in np.ndenumerate(a3):
    print(pos, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [64]:
#encontrar valores que cumpla con determinados criterios
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [65]:
np.where(a3==10)

(array([], dtype=int64), array([], dtype=int64))

In [66]:
np.where(a3 < 10)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [67]:
#podemos filtrar los array como lo hemos hecho con las listas. Para una dimesión es sencillo. Sin el where.
a1[a1>1]

array([  6.21052632,  11.42105263,  16.63157895,  21.84210526,
        27.05263158,  32.26315789,  37.47368421,  42.68421053,
        47.89473684,  53.10526316,  58.31578947,  63.52631579,
        68.73684211,  73.94736842,  79.15789474,  84.36842105,
        89.57894737,  94.78947368, 100.        ])

In [69]:
#Rangos.
#una dimensión
a1[:1]


array([1.])

In [70]:
#dos dimensiones
a2[:2, :1]

array([[1],
       [4]])

In [71]:
a2[(a2>1) & (a2 % 2 == 0)]

array([2, 4, 6])

In [72]:
#unir datos. CONCATENATE arrays que pueden tener distintas dimensiones. En el ejemplo se hace sobre el eje X. Une por columnas.

arr1 = np.array ([[1, 2, 3],[4, 5, 6]])
arr2 = np.array ([[7, 8, 9],[10, 11, 12]])

arr = np.concatenate((arr1, arr2))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#STACK apila los arrays. Pensado para arrays de una sola dimensión
arrs = np.stack((arr1, arr2), axis=0)
arrs

In [86]:
#hacer subconjunto del array.
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
splitted = np.array_split(arr, 3)
splitted

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [90]:
#faltan datos, función SUM
arr = np.array([1, 2, np.nan, 7, 4, 0])
print(arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [94]:
#cuando encuentre el vacio que lo reemplace o quite
lista = []

for pos in range(len(arr)):
    if np.isnan(arr[pos]):
        arr[pos] = 0
print (arr)

[1. 2. 0. 7. 4. 0.]


In [95]:
#generar listas a partir de un FOR anidado. Iteramos y almacenamos en X cada elemento. 
lista = [x for x in arr]
lista

[1.0, 2.0, 0.0, 7.0, 4.0, 0.0]

In [96]:
#en bucles anindados el if va después. 
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([1., 2., 0., 7., 4., 0.])

In [97]:
#genera true or false en función de los valores internos que tiene el array. El logical_not hace una evaluación sobre el array
arr[np.logical_not(np.isnan(arr))]

array([1., 2., 0., 7., 4., 0.])

In [100]:
#eliminar vacios
arr[np.isfinite(arr)]

array([1., 2., 0., 7., 4., 0.])

In [101]:
#generar copias y vistas de los datos. La vista es una reprenstación del objeto original con las condiciones que queramos indicar. Enternder los datos
# nuestro array está formado por floats en un principio. Si le cambio el tipo...
copia = arr.copy()
vista = arr.view()

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

arr[0] = 67

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

original: [1. 2. 0. 7. 4. 0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [1. 2. 0. 7. 4. 0.]
original: [67.  2.  0.  7.  4.  0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [67.  2.  0.  7.  4.  0.]


In [102]:
arr.dtype

dtype('float64')

In [103]:
vista = arr.view(dtype=np.int32)
print('vista:', vista)

vista: [         0 1079033856          0 1073741824          0          0
          0 1075576832          0 1074790400          0          0]
