In [2]:
import numpy as np



In [4]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr.reshape([2,3,2])
print(arr2)
arro=arr2.reshape(12)
arro


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1,1],[2,2,2]])

print(a+b)
print(a**2)
print(a*2)

[[2 3 4]
 [6 7 8]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]


In [15]:
a = np.array([[1,2],[4,5]])
b = np.array([[1,1],[2,2]])

print(a @ b) #Debe ser matriz cuadrada


[[ 5  5]
 [14 14]]


In [17]:
a = np.array([[1,2],[4,5]])
print(np.linalg.norm(a))

6.782329983125268


In [19]:
a = np.array([[1,2],[4,5]])
a.T #Trasponer

array([[1, 4],
       [2, 5]])

In [21]:
np.linalg.det(a)

-2.9999999999999996

In [24]:
# x + 2y = 1
# 3x + 5y = 2

a = np.array([[1,2],[3,5]])  
b = np.array([1,2])        

np.linalg.solve(a, b)

array([-1.,  1.])

In [26]:
#pudiendo añadir más dimensiones

a = np.array([[1,2,3],[3,5,4],[2,6,4]])  
b = np.array([1,2,5])        

np.linalg.solve(a, b)

array([-1.58333333,  1.41666667, -0.08333333])

In [92]:
#Ejercicio

#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

#a = np.array([1,2,3,4,5,6])
#b = np.array([[1,2,3],[4,5,6]])
#c = np.array([[1,2,3],[2,3,4],[4,5,6],[6,7,8]])
#print(a)
#print(b)
#print(c)

print(np.zeros(6))
print(np.zeros([3,2]))
print(np.zeros([2,3,4]))

[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [93]:
#Ejercicio 2.
#Crea una función que te haga un resumen estadístico básico de un array 
# (cuartiles, mediana, media, varianza, etc) si tiene una dimensión. 
# Si tiene más de una, muestra un mensaje de alerta.

a = np.array([1,2,3,4,5,6])

def calcular_datos_estadisticos(a):
    # Aplanar la matriz para calcular los cuartiles
        datos = a.flatten()
    
    # Calcular los cuartiles
        Q1 = np.percentile(datos, 25)
        Q2 = np.percentile(datos, 50)  # También conocido como la mediana
        Q3 = np.percentile(datos, 75)
        media = np.mean(datos)
        varianza = np.var(datos)
        return Q1, Q2, Q3, media, varianza    

if a.ndim == 1:
    Q1, Q2, Q3, media, varianza = calcular_datos_estadisticos(a)
    print(f"Primer cuartil (Q1): {Q1}")
    print(f"Segundo cuartil (Q2): {Q2}")
    print(f"Tercer cuartil (Q3): {Q3}")
    print(f"Media: {media}")
    print(f"Varianza: {varianza}")
else:
    print('La matriz es de más dimensiones')

 #solucion Ricardo
  #def reumen_std(arr)
     #if arr.ndim != 1:
        #return 'debe ser 1 dimension' 
     
     #resumen = {
          #'media':np.mean(arr),
          #'mediana':np.median(arr),
          #'var':np.var(arr),
          #'dev_std':np.std(arr),
          #'q1':np.percentile(arr,25),
          #'q2':np.percentile(arr,50),
          #'q':np.percentile(arr,75,
     #}
    #return resumen


Primer cuartil (Q1): 2.25
Segundo cuartil (Q2): 3.5
Tercer cuartil (Q3): 4.75
Media: 3.5
Varianza: 2.9166666666666665


In [ ]:
#Ejercicio 3.
#Crea un array de 3 dimensiones parecido al que te doy a continuación, 
# y sin ejecutar las instrucciones siguientes, intenta razonar qué números devolverán (si funcionan, claro)

arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7,8,9],[10, 11, 12]],[[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24]]])
arr # 4 x 2 x 3

arr[-1,-1,-1] #empieza por atrás, último elemento, del último bloque Sol:24
arr[0,1,:] #todos los elementos de la fila 4,5,6
arr[:,0,:]#
print (arr[:,:,-1])
arr[1,2,3] #segunda posición, del tercero... index3, ERROR
arr[2,1,0] #tercera posisción,segundo elemento posicií¡on 0 VALOR CONCRETO
arr[::2,:,:] #salta de dos en dos lo elementos


[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]


IndexError: index 2 is out of bounds for axis 1 with size 2

In [90]:
#Ejercicio 4.
#Crea un array de 3 x 3 que contenga valores aleatorios entre el 0 y el 100. 
# Tendrás que usar el submódulo random. Una vez tengas el código, 
# transfórmalo a una función que te permita crear arrays de tamaño N x N

from numpy import random
arr1 = np.random.randint(0, 100, size=(3, 3))
arr1

#random.random([3,3])*100
#def gen_arr_random(n):
    #if n<=0:return 'n<0'
    #return random.random([n,n])*100

#def crear_array_aleatorio(N):
    # Crear un array de tamaño NxN con valores aleatorios entre 0 y 100
    #array = np.random.randint(0, 101, size=(N, N))
    #return array 

array([[45, 51, 44],
       [66, 75, 72],
       [74, 68, 61]])

In [80]:
#Ejercicio 5.
#Crea una función que dependa de un número. Si la función se ejecuta con el número 5, debe devolver el siguiente array:

#1 1 1 1 1

#1 0 0 0 1

#1 0 0 0 1

#1 0 0 0 1

#1 1 1 1 1
def crear_array_numero(n):
    # Crear un array de tamaño nxn con todos los elementos en 1
    array = np.ones((n, n), dtype=int)
    
    # Rellenar el interior del array con 0s, dejando los bordes en 1
    array[1:-1, 1:-1] = 0
    
    return array

# Crear un array de 5x5
num_5 = crear_array_numero(5)

print("Array de 5x5 con bordes en 1 y el interior en 0:")
print(num_5)

Array de 5x5 con bordes en 1 y el interior en 0:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [97]:
#Ejercicio 6.
#Crea una función que te detecte las dimensiones de un array, y te diga cuántos datos faltantes contiene. 
# Crea unos datos de ejemplo para comprobarlo.


arr = np.ones([3,3])

arr[1,1]=np.nan
arr[2,0]=np.nan
arr

#np.isnan(arr)
#print(arr.flatten()) para aplanar en una dimension

def dims_and_nams(arr):
    return {}


[ 1.  1.  1.  1. nan  1. nan  1.  1.]


In [114]:
#Ejercicio 7.
#Crea una función que te calcule los márgenes de una tabla, es decir, la suma por columnas, la suma por filas y el total. 
# Idealmente, añadelo a la tabla original

arr = np.array( [[3,2,1,2],[6,7,9,5]] )

#sumar filas
#np.sum(arr,axis=0)
#sumar columnas
#np.sum(arr,axis=1)
#total
#np.sum(arr)

def gen_tabla_margenes(arr):
    sum_col=np.sum(arr,axis=0)
    sum_fil=np.sum(arr, axis=1).reshape(-1,1)
    total=np.sum(arr)

    tabla_filas = np.hstack((arr, sum_fil))
    ultima_fila=np.hstack([sum_col,total])
    tabla_margenes=np.vstack([tabla_filas, ultima_fila])
    return tabla_margenes
print(tabla_margenes)

[[ 3  2  1  2  8]
 [ 6  7  9  5 27]
 [ 9  9 10  7 35]]


In [115]:
#Ejercicio 8.
#Crea una función que dados dos arrays X e Y, 
# te calcule el coeficiente de correlación entre ellos usando la siguiente fórmula

#  https://wikimedia.org/api/rest_v1/media/math/render/svg/2b9c2079a3ffc1aacd36201ea0a3fb2460dc226f

image.png

x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])

NameError: name 'image' is not defined

In [118]:
x = np.array([2,3,4,6,7,8,9,7])
y = np.array([5,6,8,5,10,8,9,5])
#corr: -1,1
media_x=np.mean(x)
media_y=np.mean(y)

In [120]:
numerador=np.sum((x-media_x)*(y-media_y))
numerador


18.0

In [123]:
denominador=np.sqrt(np.sum((x-media_x)**2))*np.sqrt(np.sum((y-media_y)**2))
denominador


34.8998567332303

In [125]:
corr=numerador/denominador
corr

0.5157614295551275

In [127]:
def coef_corr(x,y):
    if (x.ndim != 1 or y.ndim != 1) and (len(x) != len(y)):
        return 'x e y no tienen la misma dimension'

    media_x=np.mean(x)
    media_y=np.mean(y)
    numerador=np.sum((x-media_x)*(y-media_y))
    denominador=np.sqrt(np.sum((x-media_x)**2))*np.sqrt(np.sum((y-media_y)**2))

    if denominador == 0:
        return 'Error denominador, 0'
    corr=numerador/denominador
    return corr