In [6]:
import numpy as np

In [8]:


arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr.reshape([2,6])
print(arr2)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
#si tengo una matriz a la que quiero aplicarle una operación, puedo hacerlo elemento por elemento

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

print(a+b)

print(a**2)

[[2 3 4]
 [6 7 8]]
[[ 1  4  9]
 [16 25 36]]


In [19]:
#Podemos utilizar un algebra matricial

a = np.array ([1, 2, 3])
b = np.array([1, 0, 1])

print(a @ b)

print(a.dot (b))


4
4


In [25]:
print(np.linalg.norm(a))

3.7416573867739413


In [27]:
#x+2Y = 1
#3X+5Y = 2
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

np.linalg.solve(a,b)

array([-1.,  1.])

In [29]:
#se podría añadir otro elemento
a = np.array([[1,2,4],[3,5,2], [3,5,7]])
b = np.array([1,2,4])

np.linalg.solve(a,b)

array([ 5.4, -3. ,  0.4])

In [ ]:
#trasponer una matriz, intercambiar sus posiciones
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
#EJERCICIOS 16/01