In [4]:
#1. Crea una matriz 1D con valores que van del 0 al 9
import numpy as np


In [30]:
array1 = np.array ([0, 1, 3, 4, 5, 6, 7, 8, 9])
print(array1)

[0 1 3 4 5 6 7 8 9]


In [31]:
#2. Convierte una matriz 1D en una matriz 2D con dos filas. 
#Usamos la función reshape de NumPy para transformar la matriz 1D en una matriz bidimensional (2D) con dos filas. 
# El parámetro -1 le indica a NumPy que calcule automáticamente el número de columnas necesario para acomodar todos los elementos.

#creamos una matriz 1D: 1 fila
array_1d = np.array ([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print (array_1d)
# convertimos la matriz 1D en una matriz 2D con 2 filas y 5 columnas
array_2d = array_1d.reshape(2, -1)
print (array_2d)

[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [32]:
#3. Multiplica una matriz de 5x3 por una matriz de 3x2

array1= np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9], 
    [10, 11, 12],
    [13, 14, 15]])


array2 = np.array([
    [1, 2], 
    [3, 4],
    [5, 6]])

print(array1)

print(array2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]


In [39]:
multiplicacion = np.dot (array1, array2)
print(multiplicacion)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [7]:
#4. Extrae todos los números impares de una matriz del 1 al 10.
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
#Aquí estás creando un array de NumPy con valores del 1 al 10. np.array() es una función de NumPy que transforma una lista de Python en un array de NumPy.
impares = array[array % 2 != 0] 
#operación de selección basada en una condición lógica. array % 2 != 0 crea un array booleano donde cada elemento es True si el elemento correspondiente en array es impar, y False si es par. 
#Usando este array booleano como índice, seleccionas solo los elementos que son impares y los asignas a la variable impares.
print(impares)


[1 3 5 7 9]


In [8]:
#5.  Reemplaza todos los números impares en una matriz del 1 al 10 con -1.
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[array%2 !=0]=-1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
#6. Convierte una matriz 1D en una matriz booleana donde todos los valores positivos se convierten en Verdaderos.